menu:
  Blog: /
  #   GitHub: https://github.com/MiKatre
  Archive: archives/
  Feed: atom.xml

favicon: favicon.png
logo: favicon.png

# Comment
# e.g disqus: claymcleod
disqus:

# Analytics
ga: UA-78677033-5

# Copyright Infomation
startyear: 2022

# Image Credits
enable_image_credit: true
